# -*- coding: utf-8 -*-

# 第1引数に年度、第2引数にa or b(前期or後期)
# 前期or後期の判断
if ARGV[1] == "a" then
  period="前期"
elsif ARGV[1] == "b" then
  period="後期"
end

w = open("../../httpd/html/assessment/#{ARGV[0]}#{ARGV[1]}/purpose.php","w")
w.puts("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd\">")
w.puts("<html lang=\"ja\">")
w.puts("")
w.puts("<head>")
w.puts("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">")
w.puts("  <meta http-equiv=\"Content-Style-Type\" content=\"text/css\">")
w.puts("  <meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\">")
w.puts("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./r.css\">")
w.puts("  <title>#{ARGV[0]}年度#{period}授業評価アンケート-実施目的・注意事項</title>")
w.puts("</head>")
w.puts("")
w.puts("<body>")
w.puts("  <div id=\"container\">")
w.puts("    <div id=\"main\">")
w.puts("      <?php")
w.puts("      include(\"./global.php\");")
w.puts("      title();")
w.puts("      ?>")
w.puts("")
w.puts("      <center>")
w.puts("      <table border=\"3\">")
w.puts("        <tr>")
w.puts("          <td id=\"menu\"><a href=\"./index.html\">トップページ</a></td>")
w.puts("          <td id=\"menu\"><a href=\"./purpose.php\">実施目的・注意事項</a></td>")
w.puts("          <td id=\"menu\"><a href=\"./subjects.php\">対象科目</a></td>")
w.puts("          <td id=\"menu\"><a href=\"./process.php\">回答の手順</a></td>")
w.puts("          <td id=\"menu\"><a href=\"./enq.php\">設問一覧</a></td>")
w.puts("          <td id=\"menu\"><a href=\"./result/output.php\">現在の回答状況</a></td>")
w.puts("        </tr>")
w.puts("      </table>")
w.puts("")
w.puts("      </center>")
w.puts("")
w.puts("")
w.puts("      <h2 class=\"paragraph\">実験目的</h2>")
w.puts("      <p>今回の「授業評価アンケート」は、情報工学科が提供している専門科目に 対する、学生主体による評価を行うことが目的です。</p>")
w.puts("")
w.puts("      <h2 class=\"paragraph\">注意事項</h2>")
w.puts("      <p>以下に、今回のアンケート回答に関する注意事項をあげます。<br>これらをよく読んだ上で回答してください。</p>")
w.puts("      <ul>")
w.puts("        <li><font color=\"red\">#{ARGV[0]}年度#{period}</font>において<font color=\"red\">登録している講義すべて</font>の評価を行う必要があります。</li>")
w.puts("        <li>受講している科目は個人的理由で『<font color=\"red\">単位取得をあきらめている</font>』場合でも回答してください。貴重なデータとなります。</li>")
w.puts("        <li><font color=\"red\">情報工学実験1,2</font>は、担当教員毎に評価します。</li>")
w.puts("        <li><font color=\"red\">情報工学実験3,4</font>は、テーマ毎に評価します。</li>")
w.puts("        <li>工業数学などの専門科目に関して、情報工学科指定外のクラスは対象外となりますので注意してください。</li>")
w.puts("        <li>登録科目の追加・削除も可能です。</li>")
w.puts("        <li>一度入力した評価でも、あとで修正することができます。</li>")
w.puts("        <li>実験・実習系は座学系に比べ、評価項目が若干多くなっています。</li>")
w.puts("      </ul>")
w.puts("")
w.puts("      <h2 class=\"paragraph\">データ管理方針</h2>")
w.puts("      <p>今回収集したデータについて、アンケートにより得られた情報そのものを第三者に公開することや、個人が特定できるような状態にすることは一切行いません。</p>")
w.puts("")
w.puts("      <?php")
w.puts("      back();")
w.puts("      ?>")
w.puts("")
w.puts("    </div>")
w.puts("  </div>")
w.puts("</body>")
w.puts("</html>")

w.close
